export const Notes = ['C', 'D', 'E', 'F', 'G', 'A', 'B'];
export const Accidentals = ['', '#', '♭'];
export const Keys = [
  'C♭ major',
  'G♭ major',
  'D♭ major',
  'A♭ major',
  'E♭ major',
  'B♭ major',
  'F major',
  'C major',
  'G major',
  'D major',
  'A major',
  'E major',
  'B major',
  'F# major',
  'C# major',
  'a minor',
  'e minor',
  'b minor',
  'f# minor',
  'c# minor',
  'g# minor',
  'd# minor',
  'e♭ minor',
  'b♭ minor',
  'f minor',
  'c minor',
  'g minor',
  'd minor'
];
export const Intervals = [
  { name: 'second', quality: ['major', 'minor', 'augmented'] },
  { name: 'third', quality: ['major', 'minor'] },
  { name: 'fourth', quality: ['diminished', 'perfect', 'augmented'] },
  { name: 'fifth', quality: ['diminished', 'perfect', 'augmented'] },
  { name: 'sixth', quality: ['major', 'minor'] },
  { name: 'seventh', quality: ['diminished', 'major', 'minor'] },
  { name: 'octave', quality: ['perfect'] }
];
export const ChordQuality = [
  'major',
  'minor',
  'dominant seventh',
  'minor seventh',
  'diminished seventh'
];
export const KEYS = [
  { name: 'Cb', type: 'major' },
  { name: 'Gb', type: 'major' },
  { name: 'Db', type: 'major' },
  { name: 'Ab', type: 'major' },
  { name: 'Eb', type: 'major' },
  { name: 'Bb', type: 'major' },
  { name: 'F', type: 'major' },
  { name: 'C', type: 'major' },
  { name: 'G', type: 'major' },
  { name: 'D', type: 'major' },
  { name: 'A', type: 'major' },
  { name: 'E', type: 'major' },
  { name: 'B', type: 'major' },
  { name: 'F#', type: 'major' },
  { name: 'C#', type: 'major' },
  { name: 'A', type: 'minor' },
  { name: 'E', type: 'minor' },
  { name: 'B', type: 'minor' },
  { name: 'F#', type: 'minor' },
  { name: 'C#', type: 'minor' },
  { name: 'G#', type: 'minor' },
  { name: 'D#', type: 'minor' },
  { name: 'Eb', type: 'minor' },
  { name: 'Bb', type: 'minor' },
  { name: 'F', type: 'minor' },
  { name: 'C', type: 'minor' },
  { name: 'G', type: 'minor' },
  { name: 'D', type: 'minor' }
];
